
// Generated by Cadence Genus(TM) Synthesis Solution 19.10-p002_1
// Generated on: Mar 15 2025 04:47:47 EDT (Mar 15 2025 08:47:47 UTC)

// Verification Directory fv/traffic_light_controller 

module traffic_light_controller(clk, rst, car_light, pedestrian_light,
     seg_display);
  input clk, rst;
  output [2:0] car_light;
  output pedestrian_light;
  output [7:0] seg_display;
  wire clk, rst;
  wire [2:0] car_light;
  wire pedestrian_light;
  wire [7:0] seg_display;
  wire [3:0] seconds;
  wire [1:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_28, n_29, n_30, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_55, n_56, n_57, n_58, n_60, n_61, n_62;
  wire n_63, n_66, n_69;
  assign seg_display[7] = 1'b0;
  assign pedestrian_light = car_light[0];
  AND2_X1 g1693__8780(.A1 (n_69), .A2 (n_24), .ZN (seg_display[6]));
  DFF_X1 \count_inst_counter_reg[1] (.CK (clk), .D (n_62), .Q
       (seconds[1]), .QN (UNCONNECTED));
  AND3_X1 g1692__4296(.A1 (n_69), .A2 (n_63), .A3 (n_47), .ZN
       (seg_display[5]));
  AND2_X1 g1695__3772(.A1 (n_69), .A2 (n_66), .ZN (seg_display[3]));
  SDFFS_X1 \count_inst_counter_reg[2] (.SN (1'b1), .CK (clk), .D
       (n_51), .SE (seconds[2]), .SI (n_46), .Q (seconds[2]), .QN
       (UNCONNECTED0));
  AND2_X1 g1700__1474(.A1 (n_61), .A2 (n_66), .ZN (seg_display[0]));
  SDFFS_X1 \count_inst_counter_reg[0] (.SN (1'b1), .CK (clk), .D
       (n_56), .SE (seconds[0]), .SI (n_57), .Q (seconds[0]), .QN
       (UNCONNECTED1));
  DFF_X1 \count_inst_counter_reg[3] (.CK (clk), .D (n_53), .Q
       (seconds[3]), .QN (UNCONNECTED2));
  OAI211_X1 g1696__4547(.A (n_45), .B (n_63), .C1 (n_48), .C2 (n_43),
       .ZN (seg_display[4]));
  INV_X1 g1707(.A (n_58), .ZN (n_62));
  AOI21_X1 g1702__9682(.A (n_60), .B1 (n_50), .B2 (n_23), .ZN (n_69));
  INV_X1 g1703(.A (n_60), .ZN (n_61));
  AND2_X1 g1704__2683(.A1 (n_49), .A2 (n_55), .ZN (seg_display[1]));
  AOI22_X1 g1710__1309(.A1 (n_57), .A2 (seconds[1]), .B1 (n_56), .B2
       (n_1), .ZN (n_58));
  OAI21_X1 g1705__6877(.A (n_55), .B1 (n_40), .B2 (n_44), .ZN (n_60));
  AND2_X1 g1701__2900(.A1 (n_63), .A2 (n_55), .ZN (seg_display[2]));
  INV_X1 g1708(.A (n_52), .ZN (n_53));
  AOI22_X1 g1711__2391(.A1 (n_38), .A2 (seconds[3]), .B1 (n_51), .B2
       (seconds[2]), .ZN (n_52));
  DFF_X1 \state_reg[1] (.CK (clk), .D (n_36), .Q (state[1]), .QN (n_0));
  NAND2_X1 g1712__7675(.A1 (n_50), .A2 (n_21), .ZN (n_66));
  NAND3_X1 g1714__7118(.A1 (n_50), .A2 (n_48), .A3 (n_47), .ZN (n_49));
  OAI21_X1 g1713__8757(.A (n_42), .B1 (n_37), .B2 (n_34), .ZN (n_46));
  NAND3_X1 g1709__1786(.A1 (n_50), .A2 (n_19), .A3 (n_44), .ZN (n_45));
  DFF_X1 \state_reg[0] (.CK (clk), .D (n_41), .Q (state[0]), .QN
       (UNCONNECTED3));
  OR4_X1 g1706__5953(.A1 (n_39), .A2 (n_43), .A3 (n_29), .A4 (n_18),
       .ZN (n_63));
  INV_X1 g1715(.A (n_42), .ZN (n_57));
  OAI21_X1 g1727__5703(.A (n_32), .B1 (n_28), .B2 (rst), .ZN (n_41));
  OR2_X1 g1719__7114(.A1 (n_39), .A2 (n_35), .ZN (n_40));
  NAND2_X1 g1718__5266(.A1 (n_38), .A2 (n_37), .ZN (n_42));
  INV_X1 g1723(.A (n_33), .ZN (n_36));
  NAND2_X1 g1721__2250(.A1 (n_39), .A2 (n_35), .ZN (n_55));
  NOR2_X1 g1722__6083(.A1 (n_39), .A2 (n_30), .ZN (n_50));
  AND2_X1 g1720__2703(.A1 (n_56), .A2 (n_34), .ZN (n_51));
  AOI21_X1 g1725__5795(.A (n_25), .B1 (n_38), .B2 (car_light[0]), .ZN
       (n_33));
  NAND2_X1 g1729__7344(.A1 (n_38), .A2 (car_light[1]), .ZN (n_32));
  INV_X1 g1724(.A (n_56), .ZN (n_37));
  XOR2_X1 g1728__1840(.A (n_17), .B (n_22), .Z (n_39));
  AOI211_X1 g1726__5019(.A (rst), .B (n_20), .C1 (seconds[3]), .C2
       (seconds[1]), .ZN (n_56));
  NAND2_X1 g1731__1857(.A1 (n_30), .A2 (n_29), .ZN (n_35));
  NAND2_X1 g1732__9906(.A1 (n_26), .A2 (car_light[2]), .ZN (n_28));
  NOR2_X1 g1734__8780(.A1 (n_26), .A2 (rst), .ZN (n_38));
  NOR3_X1 g1730__4296(.A1 (n_24), .A2 (n_2), .A3 (rst), .ZN (n_25));
  INV_X1 g1735(.A (n_47), .ZN (n_23));
  OAI22_X1 g1738__3772(.A1 (n_15), .A2 (n_6), .B1 (n_5), .B2
       (seconds[2]), .ZN (n_22));
  INV_X1 g1737(.A (n_30), .ZN (n_43));
  INV_X1 g1736(.A (n_21), .ZN (n_48));
  OAI22_X1 g1733__1474(.A1 (n_13), .A2 (n_3), .B1 (n_7), .B2 (n_11),
       .ZN (n_20));
  NAND2_X1 g1739__4547(.A1 (n_19), .A2 (n_18), .ZN (n_47));
  NOR2_X1 g1740__9682(.A1 (n_19), .A2 (n_18), .ZN (n_21));
  INV_X1 g1742(.A (n_24), .ZN (n_26));
  XNOR2_X1 g1741__2683(.A (n_14), .B (n_16), .ZN (n_30));
  NAND4_X1 g1743__1309(.A1 (n_10), .A2 (n_17), .A3 (n_44), .A4 (n_16),
       .ZN (n_24));
  INV_X1 g1744(.A (n_19), .ZN (n_29));
  XOR2_X1 g1745__6877(.A (n_12), .B (n_9), .Z (n_19));
  INV_X1 g1747(.A (n_14), .ZN (n_15));
  NOR2_X1 g1746__2900(.A1 (n_8), .A2 (seconds[3]), .ZN (n_13));
  OAI21_X1 g1748__2391(.A (seconds[1]), .B1 (n_12), .B2 (n_11), .ZN
       (n_14));
  INV_X1 g1749(.A (n_9), .ZN (n_10));
  HA_X1 g1750__7675(.A (n_4), .B (seconds[1]), .CO (n_8), .S (n_9));
  XNOR2_X1 g1755__7118(.A (n_11), .B (seconds[3]), .ZN (n_17));
  NOR2_X1 g1751__8757(.A1 (n_6), .A2 (seconds[3]), .ZN (n_7));
  INV_X1 g1752(.A (n_44), .ZN (n_18));
  HA_X1 g1753__1786(.A (car_light[0]), .B (seconds[0]), .CO (n_12), .S
       (n_44));
  HA_X1 g1754__5953(.A (n_5), .B (seconds[2]), .CO (n_6), .S (n_16));
  INV_X1 g1758(.A (n_4), .ZN (n_11));
  AOI21_X1 g1757__5703(.A (seconds[2]), .B1 (n_5), .B2 (seconds[0]),
       .ZN (n_3));
  NAND2_X1 g1759__7114(.A1 (n_2), .A2 (n_5), .ZN (n_4));
  HA_X1 g1756__5266(.A (seconds[1]), .B (seconds[0]), .CO (n_34), .S
       (n_1));
  INV_X1 g1760(.A (n_2), .ZN (car_light[1]));
  INV_X1 g1762(.A (n_5), .ZN (car_light[0]));
  NAND2_X1 g1761__2250(.A1 (state[0]), .A2 (n_0), .ZN (n_2));
  OR2_X1 g1764__6083(.A1 (state[0]), .A2 (n_0), .ZN (n_5));
  NOR2_X1 g1763__2703(.A1 (state[1]), .A2 (state[0]), .ZN
       (car_light[2]));
endmodule

